config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home', as: :home
  get 'about', to: 'pages#about', as: :about
  get 'film', to: 'pages#film', as: :film
  get 'mv', to: 'pages#mv', as: :mv
  get 'docu', to: 'pages#docu', as: :docu
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def film
  end

  def mv
  end

  def docu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- <meta name="description" content="DemoMap | Real time info for your demonstration. Participate actively and safely in demonstrations.">
    <meta property="og:title" content="DemoMap | Know Where to March" />
    <meta property="og:description" content="DemoMap | Real time info for your demonstration. Participate actively and safely in demonstrations." />
    <meta property="og:image" content='<#%= image_url 'banner_demo.jpg' %>'/>
    <meta property="og:image:width" content='1200'/>
    <meta property="og:image:height" content='630'/> -->



    <title>Tjwebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/navbar' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="row justify-content-center">
  <div id="about">
  </div>
</div>
<!--
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <#%= "Lorem ipsum dolor sit amet, consectetur adipisicing elit " * 100 %>
    </div>
  </div>
</div>
 -->

app/views/pages/docu.html.erb
<h1>Pages#docu</h1>
<p>Find me in app/views/pages/docu.html.erb</p>

app/views/pages/film.html.erb
<h1>Pages#film</h1>
<p>Find me in app/views/pages/film.html.erb</p>

app/views/pages/home.html.erb
<!-- <div id="content" style="height: 2000px; ">
  <br>
  <br>
  <br>
  <br>
  <br>
  <h1>homepage</h1>
</div> -->

app/views/pages/mv.html.erb
<h1>Pages#mv</h1>
<p>Find me in app/views/pages/mv.html.erb</p>

app/views/shared/_navbar.html.erb
<div id="navigation">
  <div class="row">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
       <!--  <div class="navigation-logo">
          <a class="navigation-logo-link" href="/">
            <span>TANJA EGEN</span>
          </a>
        </div> -->
        <ul class="navigation-items">
          <li class="navigation-item navigation-logo-link">
            <%= link_to "TANJA EGEN", href="/" , class: "nav-link" %>
          </li>
          <li class="navigation-item">
            <%= link_to "film", film_path, class: "nav-link" %>
          </li>
          <li class="navigation-item">
            <%= link_to "documentaries", docu_path, class: "nav-link" %>
          </li>
          <li class="navigation-item">
            <%= link_to "music videos", mv_path, class: "nav-link" %>
          </li>
          <li class="navigation-item">
            <%= link_to "about", about_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
  </div>
</div>